package com.zl.bgec.basicapi.order.po;


import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.hibernate.annotations.GenericGenerator;

/**
 * TblOrder generated by hbm2java
 */
@Entity
@Table(name = "tbl_order")
public class Order implements java.io.Serializable{

	private static final long serialVersionUID = 1;
	private String shopPhone;//卖家电话
	/**
	 * id
	 */
	private String id;
	/**
	 * 订单编号
	 */
	private String orderNo;
	/**
	 * 买家编号
	 */
	private String buyerNo;
	/**
	 * 卖家编号
	 */
	private String sellerNo;
	/**
	 * 下单人电话
	 */
	private String buyerPhone;
	/**
	 * 优惠总金额
	 */
	private Double discountTotal;
	/**
	 * 配送费用总额
	 */
	private Double deliveryFeeTotal;
	/**
	 * 订单付费总计
	 */
	private Double feeTotal;
	/**
	 * 订单付费总计
	 */
	private Double priceTotal;
	/**
	 * 付款方式
	 */
	private String paymentType;
	/**支付银行或某些支付平台编号(银行，支付宝，财富通)*/
	private String paymentBank;
	/**
	 * 递送方式
	 */
	private String deliveryType;//1送货上面，2到店自提
	/**
	 * 支付时间
	 */
	private Date paymentTime;
	/**
	 * 已付金额
	 */
	private Double paidTotal;
	/**
	 * 订单基本状态
	 */
	private String basicState;
	/**
	 * 订单支付状态
	 */
	private String paymentState;
	/**
	 * 优惠活动名
	 */
//	private String promotions;
	/**
	 * 貨品數量
	 */
//	private Integer prodQuantity;
	/**
	 * 备注信息
	 */
	private String remark;
	/**
	 * 订单生成时间戳
	 */
	private Long orderTimestamp;
	/**
	 * 删除状态
	 */
	private Byte deleteFlag;//0未删除，1已删除
	/**
	 * 创建时间
	 */
	private Date createTime;
	/**
	 * 修改时间
	 */
	private Date updateTime;
	/**
	 * 买家留言
	 */
	private String buyerMessage;
	/**
	 * 买家昵称
	 */
	private String buyerNickName;

	/**
	 * 支付流水号
	 */
	private String paymentSequence;
	
	/**订单取消原因**/
	private String cancelReason;
	/**取消时间*/
	private Date cancelTime;
	
	private String shopNo;
	private OrderAddress orderAddress;
	
	private List<OrderLog> orderLogs;
	
	private List<OrderItem> orderItems;
	private String orderCouponsNo;
	private List<OrderCoupons> orderCoupons;
		
	private OrderReturn orderReturn;
	private String deliveryName;//送货人名称
	private String deliveryPhone;//送货人手机
	private String deliveryDescription;//送货人描述
	private String expressCompany;//快递公司
	private String expressNo;//快递单号
	
	private String orderType;
	private Integer alreadyCount;
	private Integer coupCount;
	private Double discountAmount;
	private Integer limitCount;
	private Date promStartTime;
	private Date promEndTime;
	private String groupMsg;
	
	
	public Order() {
	}

	public Order(String id, String orderNo, String buyerNo, String sellerNo) {
		this.id = id;
		this.orderNo = orderNo;
		this.buyerNo = buyerNo;
		this.sellerNo = sellerNo;
	}

	public Order(String id, String orderNo, String buyerNo, String sellerNo,
			Double priceTotal, Double discountTotal, Double deliveryFeeTotal,
			Double feeTotal,
			String paymentType, String deliveryType, Date paymentTime,
			Double paidTotal, String basicState, String paymentState,
			 String refundState, String promotions,
			Integer prodQuantity,  String remark, Long orderTimestamp,
			Byte deleteFlag, Date createTime, Date updateTime) {
		this.id = id;
		this.orderNo = orderNo;
		this.buyerNo = buyerNo;
		this.sellerNo = sellerNo;
//		this.priceTotal = priceTotal;
		this.discountTotal = discountTotal;
		this.deliveryFeeTotal = deliveryFeeTotal;
		this.feeTotal = feeTotal;
		this.paymentType = paymentType;
		this.deliveryType = deliveryType;
		this.paymentTime = paymentTime;
		this.paidTotal = paidTotal;
		this.basicState = basicState;
		this.paymentState = paymentState;
//		this.refundState = refundState;
//		this.promotions = promotions;
//		this.prodQuantity = prodQuantity;
		this.remark = remark;
		this.orderTimestamp = orderTimestamp;
		this.deleteFlag = deleteFlag;
		this.createTime = createTime;
		this.updateTime = updateTime;
	}

    @GenericGenerator(name = "generator", strategy = "uuid.hex")
    @GeneratedValue(generator = "generator")
	@Id
	@Column(name = "id", unique = true, nullable = false, length = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "order_no", unique = true, nullable = false, length = 32)
	public String getOrderNo() {
		return this.orderNo;
	}

	public void setOrderNo(String orderNo) {
		this.orderNo = orderNo;
	}

	@Column(name = "buyer_no", nullable = false, length = 32)
	public String getBuyerNo() {
		return this.buyerNo;
	}

	public void setBuyerNo(String buyerNo) {
		this.buyerNo = buyerNo;
	}

	@Column(name = "seller_no", nullable = false, length = 32)
	public String getSellerNo() {
		return this.sellerNo;
	}

	public void setSellerNo(String sellerNo) {
		this.sellerNo = sellerNo;
	}


	@Column(name = "discount_total", precision = 22, scale = 0)
	public Double getDiscountTotal() {
		return this.discountTotal;
	}

	public void setDiscountTotal(Double discountTotal) {
		this.discountTotal = discountTotal;
	}

	@Column(name = "delivery_fee_total", precision = 22, scale = 0)
	public Double getDeliveryFeeTotal() {
		return this.deliveryFeeTotal;
	}

	public void setDeliveryFeeTotal(Double deliveryFeeTotal) {
		this.deliveryFeeTotal = deliveryFeeTotal;
	}

	@Column(name = "fee_total", precision = 22, scale = 0)
	public Double getFeeTotal() {
		return this.feeTotal;
	}

	public void setFeeTotal(Double feeTotal) {
		this.feeTotal = feeTotal;
	}

	@Column(name = "payment_type", length = 50)
	public String getPaymentType() {
		return this.paymentType;
	}

	public void setPaymentType(String paymentType) {
		this.paymentType = paymentType;
	}

	@Column(name = "delivery_type", length = 50)
	public String getDeliveryType() {
		return this.deliveryType;
	}

	public void setDeliveryType(String deliveryType) {
		this.deliveryType = deliveryType;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "payment_time", length = 19)
	public Date getPaymentTime() {
		return this.paymentTime;
	}

	public void setPaymentTime(Date paymentTime) {
		this.paymentTime = paymentTime;
	}

	@Column(name = "paid_total", precision = 22, scale = 0)
	public Double getPaidTotal() {
		return this.paidTotal;
	}

	public void setPaidTotal(Double paidTotal) {
		this.paidTotal = paidTotal;
	}

	@Column(name = "basic_state", length = 50)
	public String getBasicState() {
		return this.basicState;
	}

	public void setBasicState(String basicState) {
		this.basicState = basicState;
	}

	@Column(name = "payment_state", length = 50)
	public String getPaymentState() {
		return this.paymentState;
	}

	public void setPaymentState(String paymentState) {
		this.paymentState = paymentState;
	}

//	@Column(name = "promotions", length = 2000)
//	public String getPromotions() {
//		return this.promotions;
//	}
//
//	public void setPromotions(String promotions) {
//		this.promotions = promotions;
//	}


	@Column(name = "remark", length = 2000)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "order_timestamp")
	public Long getOrderTimestamp() {
		return this.orderTimestamp;
	}

	public void setOrderTimestamp(Long orderTimestamp) {
		this.orderTimestamp = orderTimestamp;
	}

	@Column(name = "delete_flag")
	public Byte getDeleteFlag() {
		return this.deleteFlag;
	}

	public void setDeleteFlag(Byte deleteFlag) {
		this.deleteFlag = deleteFlag;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time")
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_time", length = 19)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	@Column(name = "buyer_msg")
	public String getBuyerMessage() {
		return buyerMessage;
	}

	public void setBuyerMessage(String buyerMessage) {
		this.buyerMessage = buyerMessage;
	}

	/** 
	 * @return paymentSequence 
	 */
	@Column(name = "payment_sequence", length = 32)
	public String getPaymentSequence() {
		return paymentSequence;
	}
	
	/** 
	 * @return paymentSequence 
	 */
	public void setPaymentSequence(String paymentSequence) {
		this.paymentSequence = paymentSequence;
	}
	
	@Column(name = "buyer_nick_name", length = 64)
	public String getBuyerNickName() {
		return buyerNickName;
	}
	
	public void setBuyerNickName(String buyerNickName) {
		this.buyerNickName = buyerNickName;
	}

	@Column(name = "cancel_reason",length=256)
	public String getCancelReason() {
		return cancelReason;
	}

	public void setCancelReason(String cancelReason) {
		this.cancelReason = cancelReason;
	}
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "cancel_time")
	public Date getCancelTime() {
		return cancelTime;
	}

	public void setCancelTime(Date cancelTime) {
		this.cancelTime = cancelTime;
	}

	@Column(name="payment_bank",length=32)
	public String getPaymentBank() {
		return paymentBank;
	}

	public void setPaymentBank(String paymentBank) {
		this.paymentBank = paymentBank;
	}
	@Column(name="shop_no")
	public String getShopNo() {
		return shopNo;
	}

	public void setShopNo(String shopNo) {
		this.shopNo = shopNo;
	}
	@Transient
	public OrderAddress getOrderAddress() {
		return orderAddress;
	}

	public void setOrderAddress(OrderAddress orderAddress) {
		this.orderAddress = orderAddress;
	}
	@Transient
	public List<OrderLog> getOrderLogs() {
		return orderLogs;
	}

	public void setOrderLogs(List<OrderLog> orderLogs) {
		this.orderLogs = orderLogs;
	}
	@Transient
	public List<OrderItem> getOrderItems() {
		return orderItems;
	}

	public void setOrderItems(List<OrderItem> orderItems) {
		this.orderItems = orderItems;
	}
	@Column(name = "delivery_name")
	public String getDeliveryName() {
		return deliveryName;
	}

	public void setDeliveryName(String deliveryName) {
		this.deliveryName = deliveryName;
	}

	@Column(name = "delivery_phone")
	public String getDeliveryPhone() {
		return deliveryPhone;
	}

	public void setDeliveryPhone(String deliveryPhone) {
		this.deliveryPhone = deliveryPhone;
	}

	@Column(name = "delivery_description")
	public String getDeliveryDescription() {
		return deliveryDescription;
	}

	public void setDeliveryDescription(String deliveryDescription) {
		this.deliveryDescription = deliveryDescription;
	}
	@Transient
	public List<OrderCoupons> getOrderCoupons() {
		return orderCoupons;
	}

	public void setOrderCoupons(List<OrderCoupons> orderCoupons) {
		this.orderCoupons = orderCoupons;
	}
	@Transient
	public OrderReturn getOrderReturn() {
		return orderReturn;
	}

	public void setOrderReturn(OrderReturn orderReturn) {
		this.orderReturn = orderReturn;
	}
	@Column(name = "buyer_phone")
	public String getBuyerPhone() {
		return buyerPhone;
	}

	public void setBuyerPhone(String buyerPhone) {
		this.buyerPhone = buyerPhone;
	}
	@Column(name = "price_total")
	public Double getPriceTotal() {
		return priceTotal;
	}

	public void setPriceTotal(Double priceTotal) {
		this.priceTotal = priceTotal;
	}
	@Transient
	public String getShopPhone() {
		return shopPhone;
	}

	public void setShopPhone(String shopPhone) {
		this.shopPhone = shopPhone;
	}
	@Column(name = "express_company")
	public String getExpressCompany() {
		return expressCompany;
	}

	public void setExpressCompany(String expressCompany) {
		this.expressCompany = expressCompany;
	}
	@Column(name = "express_no")
	public String getExpressNo() {
		return expressNo;
	}

	public void setExpressNo(String expressNo) {
		this.expressNo = expressNo;
	}

	@Column(name = "order_coupons_no")
	public String getOrderCouponsNo() {
		return orderCouponsNo;
	}

	public void setOrderCouponsNo(String orderCouponsNo) {
		this.orderCouponsNo = orderCouponsNo;
	}

	@Transient
	public String getOrderType() {
		return orderType;
	}

	public void setOrderType(String orderType) {
		this.orderType = orderType;
	}

	@Transient
	public Integer getAlreadyCount() {
		return alreadyCount;
	}

	public void setAlreadyCount(Integer alreadyCount) {
		this.alreadyCount = alreadyCount;
	}

	@Transient
	public Integer getCoupCount() {
		return coupCount;
	}

	public void setCoupCount(Integer coupCount) {
		this.coupCount = coupCount;
	}

	@Transient
	public Double getDiscountAmount() {
		return discountAmount;
	}

	public void setDiscountAmount(Double discountAmount) {
		this.discountAmount = discountAmount;
	}

	@Transient
	public Integer getLimitCount() {
		return limitCount;
	}

	public void setLimitCount(Integer limitCount) {
		this.limitCount = limitCount;
	}

	@Transient
	public Date getPromStartTime() {
		return promStartTime;
	}

	public void setPromStartTime(Date promStartTime) {
		this.promStartTime = promStartTime;
	}

	@Transient
	public Date getPromEndTime() {
		return promEndTime;
	}

	public void setPromEndTime(Date promEndTime) {
		this.promEndTime = promEndTime;
	}

	@Transient
	public String getGroupMsg() {
		return groupMsg;
	}

	public void setGroupMsg(String groupMsg) {
		this.groupMsg = groupMsg;
	}
	
	
}
