package com.zl.bgec.basicapi.order.po;

// Generated 2012-11-22 15:58:19 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.hibernate.annotations.GenericGenerator;

/**
 * TblOrderItem generated by hbm2java
 */
@Entity
@Table(name = "tbl_order_item")
public class OrderItem implements java.io.Serializable{

	private static final long serialVersionUID = 2096194183086811518L;
	private String id;
	private String itemNo;
	private String orderNo;
	private String prodNo;
	private Integer quantity;
	private String category;      //分类
	private String commodityNo;   //商品编号
	private String prodName;      //商品的名称+SKU规格（比如 XXX商品 红色 XL）
	private Double price;           //促销后价
	private Double groupbuyPrice;           //促销后价
//	private Double couponsFee;		//优惠券金额
//	private Double saleTotalFee;	//销售总价(促销价 × 商品的数量 )
//	private Double disCountTotalFee;//优惠总金额(商品单个的优惠金额×商品的数量)
	private String model;//规格
	private String prodPic;		    //产品图片
	private String isComment;//评价状态
	private String buyerNo;     //买家编号
	public OrderItem() {
	}

	public OrderItem(String id, String itemNo, String orderNo, String prodNo,
			Integer quantity) {
		this.id = id;
		this.itemNo = itemNo;
		this.orderNo = orderNo;
		this.prodNo = prodNo;
		this.quantity = quantity;
	}


    @GenericGenerator(name = "generator", strategy = "uuid.hex")
    @GeneratedValue(generator = "generator")
	@Id
	@Column(name = "id", unique = true, nullable = false, length = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "item_no", unique = true, nullable = false, length = 32)
	public String getItemNo() {
		return this.itemNo;
	}

	public void setItemNo(String itemNo) {
		this.itemNo = itemNo;
	}

	@Column(name = "order_no", nullable = false, length = 32)
	public String getOrderNo() {
		return this.orderNo;
	}

	public void setOrderNo(String orderNo) {
		this.orderNo = orderNo;
	}

	@Column(name = "prod_no", nullable = false, length = 32)
	public String getProdNo() {
		return this.prodNo;
	}

	public void setProdNo(String prodNo) {
		this.prodNo = prodNo;
	}

	@Column(name = "quantity", nullable = false)
	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}


	/** 
	 * @return prodName 
	 */
	@Column(name = "prod_name", length = 100)
	public String getProdName() {
		return prodName;
	}

	/**
	 * @param prodName the prodName to set
	 */
	public void setProdName(String prodName) {
		this.prodName = prodName;
	}

	/** 
	 * @return price 
	 */
	@Column(name = "price")
	public Double getPrice() {
		return price;
	}

	/**
	 * @param price the price to set
	 */
	public void setPrice(Double price) {
		this.price = price;
	}


	/** 
	 * @return category 
	 */
	@Column(name = "category",length = 32)
	public String getCategory() {
		return category;
	}

	/**
	 * @param category the category to set
	 */
	public void setCategory(String category) {
		this.category = category;
	}


	/** 
	 * @return prodPic 
	 */
	@Column(name = "prod_pic",length = 100)
	public String getProdPic() {
		return prodPic;
	}

	/**
	 * @param prodPic the prodPic to set
	 */
	public void setProdPic(String prodPic) {
		this.prodPic = prodPic;
	}
	@Column(name = "buyer_no")
	public String getBuyerNo() {
		return buyerNo;
	}

	public void setBuyerNo(String buyerNo) {
		this.buyerNo = buyerNo;
	}

	@Column(name = "commodity_no",length=32)
	public String getCommodityNo() {
		return commodityNo;
	}

	public void setCommodityNo(String commodityNo) {
		this.commodityNo = commodityNo;
	}
	@Column(name = "model")
	public String getModel() {
		return model;
	}

	public void setModel(String model) {
		this.model = model;
	}
	@Transient
	public String getIsComment() {
		return isComment;
	}

	public void setIsComment(String isComment) {
		this.isComment = isComment;
	}
	@Column(name = "groupbuy_price")
	public Double getGroupbuyPrice() {
		return groupbuyPrice;
	}

	public void setGroupbuyPrice(Double groupbuyPrice) {
		this.groupbuyPrice = groupbuyPrice;
	}




	
}
