package com.zl.bgec.basicapi.order.po;


import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

/**
 * TblOrderLog generated by hbm2java
 */
@Entity
@Table(name = "tbl_order_log")
public class OrderLog implements java.io.Serializable {

	private static final long serialVersionUID = -5876826994147425264L;
	private String id;
	private String orderNo;
	private String operatorNo;
	private String operationType;
	private String operationRemark;
	private Date operationTime;

	public OrderLog() {
	}

	public OrderLog(String id, String orderNo, String operatorNo,
			String operationType, String operationRemark, Date operationTime) {
		this.id = id;
		this.orderNo = orderNo;
		this.operatorNo = operatorNo;
		this.operationType = operationType;
		this.operationRemark = operationRemark;
		this.operationTime = operationTime;
	}

    @GenericGenerator(name = "generator", strategy = "uuid.hex")
    @GeneratedValue(generator = "generator")
	@Id
	@Column(name = "id", unique = true, nullable = false, length = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "order_no", nullable = false, length = 32)
	public String getOrderNo() {
		return this.orderNo;
	}

	public void setOrderNo(String orderNo) {
		this.orderNo = orderNo;
	}

	@Column(name = "operator_no", nullable = false, length = 32)
	public String getOperatorNo() {
		return this.operatorNo;
	}

	public void setOperatorNo(String operatorNo) {
		this.operatorNo = operatorNo;
	}

	@Column(name = "operation_type", nullable = false, length = 50)
	public String getOperationType() {
		return this.operationType;
	}

	public void setOperationType(String operationType) {
		this.operationType = operationType;
	}

	@Column(name = "operation_remark", nullable = false, length = 2000)
	public String getOperationRemark() {
		return this.operationRemark;
	}

	public void setOperationRemark(String operationRemark) {
		this.operationRemark = operationRemark;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "operation_time", nullable = false, length = 19)
	public Date getOperationTime() {
		return this.operationTime;
	}

	public void setOperationTime(Date operationTime) {
		this.operationTime = operationTime;
	}

}
