package com.zl.bgec.basicapi.common.oauth2;

import org.springframework.stereotype.Service;

@Service
public class SdkConstants {
	/**
	 * apikey
	 */
    public  String API_KEY;
    /**
     * secretKey
     */
    public  String API_SECRET;
    /**
     * 认证uri
     */
    public  String API_AUTHORIZE_SERVICE_URI;
    /**
     * 获取token的uri
     */
    public  String API_TOKEN_SERVICE_URI;
    /**
     * 授权url
     */
    public  String API_OAUTH2API_URI;
    /**
     * 授权成功回调url
     */
    public  String CLIENT_REDIRECT_URI;
    /**
     * 查询店铺分类
     */
    public  String CLIENT_LISTBIZCATEGORIES_URI;
    /**
     * 同步状态
     */
    public  String CLIENT_SYNCUSERADDSHOPSTATUS_URI;
    /**
     * 同步删除店铺url
     */
    public  String CLIENT_SYNCDELETEBUSINESS_URI;
    /**
     * 同步店铺url
     */
    public  String CLIENT_SYNCBUSINESS_URI;
    /**
     * 同步店铺收藏
     */
    public  String CLIENT_SYNCUSERFAVORITE_URI;
    /**
     * 同步取消店铺收藏
     */
    public  String CLIENT_SYNCUSERCANCELFAVORITE_URI;
    /**
     * 查询店铺收藏
     */
    public  String CLIENT_FINDBUSINESSFAVORITESTATUS_URI;
    /**
     * 发送消息openapi/sendMessageToUser
     */
    public  String CLIENT_SENDMESSAGETOUSER_URI;
    /**
     * 获取用户服务地址列表
     */
    public  String CLIENT_USERSERVERADDRESS_URI;
/**
     * 获取默认送货地址
     */
    public String CLIENT_USER_DEFAULT_SERVERADDRESS_URI;
/**
     * 领取优惠券
     */
    public  String CLIENT_RECEIVECOUPON_URI;    
    /**
     * 生成退款单
     */
    public  String CLIENT_CREATE_REFUND_RECORD;    
    /**
     * 获取用户信息
     */
    public String CLIENT_GET_USER_INFO;
    
    public SdkConstants(String aPI_KEY, String aPI_SECRET,
			String aPI_AUTHORIZE_SERVICE_URI, String aPI_TOKEN_SERVICE_URI,
			String aPI_OAUTH2API_URI, String cLIENT_REDIRECT_URI,
			String cLIENT_LISTBIZCATEGORIES_URI,
			String cLIENT_SYNCUSERADDSHOPSTATUS_URI,
			String cLIENT_SYNCDELETEBUSINESS_URI,
			String cLIENT_SYNCBUSINESS_URI, String cLIENT_SYNCUSERFAVORITE_URI,
			String cLIENT_SYNCUSERCANCELFAVORITE_URI,
			String cLIENT_FINDBUSINESSFAVORITESTATUS_URI, 
			String sERVER_URI,String cLIENT_SENDMESSAGETOUSER_URI,
			String cLIENT_USER_DEFAULT_SERVERADDRESS_URI,
			String cLIENT_RECEIVECOUPON_URI,
			String cLIENT_GET_USER_INFO) {
		super();
		API_KEY = aPI_KEY;
		API_SECRET = aPI_SECRET;
		API_AUTHORIZE_SERVICE_URI = aPI_AUTHORIZE_SERVICE_URI;
		API_TOKEN_SERVICE_URI = aPI_TOKEN_SERVICE_URI;
		API_OAUTH2API_URI = aPI_OAUTH2API_URI;
		CLIENT_REDIRECT_URI = cLIENT_REDIRECT_URI;
		CLIENT_LISTBIZCATEGORIES_URI = cLIENT_LISTBIZCATEGORIES_URI;
		CLIENT_SYNCUSERADDSHOPSTATUS_URI = cLIENT_SYNCUSERADDSHOPSTATUS_URI;
		CLIENT_SYNCDELETEBUSINESS_URI = cLIENT_SYNCDELETEBUSINESS_URI;
		CLIENT_SYNCBUSINESS_URI = cLIENT_SYNCBUSINESS_URI;
		CLIENT_SYNCUSERFAVORITE_URI = cLIENT_SYNCUSERFAVORITE_URI;
		CLIENT_SYNCUSERCANCELFAVORITE_URI = cLIENT_SYNCUSERCANCELFAVORITE_URI;
		CLIENT_FINDBUSINESSFAVORITESTATUS_URI = cLIENT_FINDBUSINESSFAVORITESTATUS_URI;
		SERVER_URI = sERVER_URI;
		CLIENT_SENDMESSAGETOUSER_URI = cLIENT_SENDMESSAGETOUSER_URI;
		CLIENT_USER_DEFAULT_SERVERADDRESS_URI = cLIENT_USER_DEFAULT_SERVERADDRESS_URI;
		CLIENT_RECEIVECOUPON_URI = cLIENT_RECEIVECOUPON_URI;
		CLIENT_GET_USER_INFO = cLIENT_GET_USER_INFO;
	}
	public SdkConstants() {
		super();
		// TODO Auto-generated constructor stub
	}
	/**
     * 接口服务器地址+端口
     */
    public String SERVER_URI;
    
	public String getAPI_KEY() {
		return API_KEY;
	}
	public void setAPI_KEY(String aPI_KEY) {
		API_KEY = aPI_KEY;
	}
	public String getAPI_SECRET() {
		return API_SECRET;
	}
	public void setAPI_SECRET(String aPI_SECRET) {
		API_SECRET = aPI_SECRET;
	}
	public String getAPI_AUTHORIZE_SERVICE_URI() {
		return API_AUTHORIZE_SERVICE_URI;
	}
	public void setAPI_AUTHORIZE_SERVICE_URI(String aPI_AUTHORIZE_SERVICE_URI) {
		API_AUTHORIZE_SERVICE_URI = aPI_AUTHORIZE_SERVICE_URI;
	}
	public String getAPI_TOKEN_SERVICE_URI() {
		return API_TOKEN_SERVICE_URI;
	}
	public void setAPI_TOKEN_SERVICE_URI(String aPI_TOKEN_SERVICE_URI) {
		API_TOKEN_SERVICE_URI = aPI_TOKEN_SERVICE_URI;
	}
	public String getAPI_OAUTH2API_URI() {
		return API_OAUTH2API_URI;
	}
	public void setAPI_OAUTH2API_URI(String aPI_OAUTH2API_URI) {
		API_OAUTH2API_URI = aPI_OAUTH2API_URI;
	}
	public String getCLIENT_REDIRECT_URI() {
		return CLIENT_REDIRECT_URI;
	}
	public void setCLIENT_REDIRECT_URI(String cLIENT_REDIRECT_URI) {
		CLIENT_REDIRECT_URI = cLIENT_REDIRECT_URI;
	}
	public String getCLIENT_LISTBIZCATEGORIES_URI() {
		return CLIENT_LISTBIZCATEGORIES_URI;
	}
	public void setCLIENT_LISTBIZCATEGORIES_URI(String cLIENT_LISTBIZCATEGORIES_URI) {
		CLIENT_LISTBIZCATEGORIES_URI = cLIENT_LISTBIZCATEGORIES_URI;
	}
	public String getCLIENT_SYNCUSERADDSHOPSTATUS_URI() {
		return CLIENT_SYNCUSERADDSHOPSTATUS_URI;
	}
	public void setCLIENT_SYNCUSERADDSHOPSTATUS_URI(
			String cLIENT_SYNCUSERADDSHOPSTATUS_URI) {
		CLIENT_SYNCUSERADDSHOPSTATUS_URI = cLIENT_SYNCUSERADDSHOPSTATUS_URI;
	}
	public String getCLIENT_SYNCDELETEBUSINESS_URI() {
		return CLIENT_SYNCDELETEBUSINESS_URI;
	}
	public void setCLIENT_SYNCDELETEBUSINESS_URI(
			String cLIENT_SYNCDELETEBUSINESS_URI) {
		CLIENT_SYNCDELETEBUSINESS_URI = cLIENT_SYNCDELETEBUSINESS_URI;
	}
	public String getCLIENT_SYNCBUSINESS_URI() {
		return CLIENT_SYNCBUSINESS_URI;
	}
	public void setCLIENT_SYNCBUSINESS_URI(String cLIENT_SYNCBUSINESS_URI) {
		CLIENT_SYNCBUSINESS_URI = cLIENT_SYNCBUSINESS_URI;
	}
	public String getCLIENT_SYNCUSERFAVORITE_URI() {
		return CLIENT_SYNCUSERFAVORITE_URI;
	}
	public void setCLIENT_SYNCUSERFAVORITE_URI(String cLIENT_SYNCUSERFAVORITE_URI) {
		CLIENT_SYNCUSERFAVORITE_URI = cLIENT_SYNCUSERFAVORITE_URI;
	}
	public String getCLIENT_SYNCUSERCANCELFAVORITE_URI() {
		return CLIENT_SYNCUSERCANCELFAVORITE_URI;
	}
	public void setCLIENT_SYNCUSERCANCELFAVORITE_URI(
			String cLIENT_SYNCUSERCANCELFAVORITE_URI) {
		CLIENT_SYNCUSERCANCELFAVORITE_URI = cLIENT_SYNCUSERCANCELFAVORITE_URI;
	}
	public String getCLIENT_FINDBUSINESSFAVORITESTATUS_URI() {
		return CLIENT_FINDBUSINESSFAVORITESTATUS_URI;
	}
	public void setCLIENT_FINDBUSINESSFAVORITESTATUS_URI(
			String cLIENT_FINDBUSINESSFAVORITESTATUS_URI) {
		CLIENT_FINDBUSINESSFAVORITESTATUS_URI = cLIENT_FINDBUSINESSFAVORITESTATUS_URI;
	}
	public String getSERVER_URI() {
		return SERVER_URI;
	}
	public void setSERVER_URI(String sERVER_URI) {
		SERVER_URI = sERVER_URI;
	}
	
	public String getCLIENT_SENDMESSAGETOUSER_URI() {
		return CLIENT_SENDMESSAGETOUSER_URI;
	}
	public void setCLIENT_SENDMESSAGETOUSER_URI(String cLIENT_SENDMESSAGETOUSER_URI) {
		CLIENT_SENDMESSAGETOUSER_URI = cLIENT_SENDMESSAGETOUSER_URI;
	}
	
	public String getCLIENT_USERSERVERADDRESS_URI() {
		return CLIENT_USERSERVERADDRESS_URI;
	}
	public void setCLIENT_USERSERVERADDRESS_URI(String cLIENT_USERSERVERADDRESS_URI) {
		CLIENT_USERSERVERADDRESS_URI = cLIENT_USERSERVERADDRESS_URI;
	}
	
	public String getCLIENT_USER_DEFAULT_SERVERADDRESS_URI() {
		return CLIENT_USER_DEFAULT_SERVERADDRESS_URI;
	}
	public void setCLIENT_USER_DEFAULT_SERVERADDRESS_URI(
			String cLIENT_USER_DEFAULT_SERVERADDRESS_URI) {
		CLIENT_USER_DEFAULT_SERVERADDRESS_URI = cLIENT_USER_DEFAULT_SERVERADDRESS_URI;
	}
	public String getCLIENT_RECEIVECOUPON_URI() {
		return CLIENT_RECEIVECOUPON_URI;
	}
	public void setCLIENT_RECEIVECOUPON_URI(String cLIENT_RECEIVECOUPON_URI) {
		CLIENT_RECEIVECOUPON_URI = cLIENT_RECEIVECOUPON_URI;
	}
	
	public String getCLIENT_CREATE_REFUND_RECORD() {
		return CLIENT_CREATE_REFUND_RECORD;
	}
	public void setCLIENT_CREATE_REFUND_RECORD(String cLIENT_CREATE_REFUND_RECORD) {
		CLIENT_CREATE_REFUND_RECORD = cLIENT_CREATE_REFUND_RECORD;
	}
	
	public String getCLIENT_GET_USER_INFO() {
		return CLIENT_GET_USER_INFO;
	}
	public void setCLIENT_GET_USER_INFO(String cLIENT_GET_USER_INFO) {
		CLIENT_GET_USER_INFO = cLIENT_GET_USER_INFO;
	}
	@Override
	public String toString() {
		return "SdkConstants [API_KEY=" + API_KEY + ", API_SECRET="
				+ API_SECRET + ", API_AUTHORIZE_SERVICE_URI="
				+ API_AUTHORIZE_SERVICE_URI + ", API_TOKEN_SERVICE_URI="
				+ API_TOKEN_SERVICE_URI + ", API_OAUTH2API_URI="
				+ API_OAUTH2API_URI + ", CLIENT_REDIRECT_URI="
				+ CLIENT_REDIRECT_URI + ", CLIENT_LISTBIZCATEGORIES_URI="
				+ CLIENT_LISTBIZCATEGORIES_URI
				+ ", CLIENT_SYNCUSERADDSHOPSTATUS_URI="
				+ CLIENT_SYNCUSERADDSHOPSTATUS_URI
				+ ", CLIENT_SYNCDELETEBUSINESS_URI="
				+ CLIENT_SYNCDELETEBUSINESS_URI + ", CLIENT_SYNCBUSINESS_URI="
				+ CLIENT_SYNCBUSINESS_URI + ", CLIENT_SYNCUSERFAVORITE_URI="
				+ CLIENT_SYNCUSERFAVORITE_URI
				+ ", CLIENT_SYNCUSERCANCELFAVORITE_URI="
				+ CLIENT_SYNCUSERCANCELFAVORITE_URI
				+ ", CLIENT_FINDBUSINESSFAVORITESTATUS_URI="
				+ CLIENT_FINDBUSINESSFAVORITESTATUS_URI + ", SERVER_URI="
				+ SERVER_URI + ",CLIENT_SENDMESSAGETOUSER_URI="+CLIENT_SENDMESSAGETOUSER_URI
				+ ",CLIENT_USER_DEFAULT_SERVERADDRESS_URI="+CLIENT_USER_DEFAULT_SERVERADDRESS_URI
				+"]";
	}
    
}
